version: '3.7'

services:
    multisensor-data-fusion-model:
        build:
            context: .
            dockerfile: Dockerfile
        image: multisensor-data-fusion-model:latest
        container_name: multisensor-data-fusion-model
        volumes:
            - ".:/logistic_regression"
        ports:
            - "5000:5000"